# -*- coding: utf-8 -*-
"""tsf_iris_clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q9Olo0uleKmmTFLlgWEig7MCtHJJsCR3

## ***IMPORTING PYTHON LIBRARIES***
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

"""## ***IMPORTING DATA SET***"""

df = pd.read_csv("/Iris (2).csv")
df.head(10)

df.drop(columns = "Id" , inplace = True)
df.tail(5)

df.info()

df.isnull().sum()

df.fillna(0)

x_df = df
x = df.iloc[:,0:4].values
x

df.plot(kind ="scatter",
          x ='SepalLengthCm',
          y ='PetalLengthCm')
plt.grid()

"""# ***Performing clustering in each iteration***"""

for i in range(1,5):
    kmeans = KMeans(n_clusters = i, max_iter = 300, n_init = 10, random_state = 0)
    a=kmeans.fit_predict(x)
    print(a)

"""# ***PRINTING CENTROIDS IN EACH ITERATION***"""

kmeans.cluster_centers_

"""# ***PLOTTING THE CLUSTERS AND CENTEROID***"""

# plotting the clusters - On the first two columns
plt.scatter(x[a == 0, 0], x[a == 0, 1], 
            s = 100, c = 'red', label = 'Iris-setosa')
plt.scatter(x[a == 1, 0], x[a == 1, 1], 
            s = 100, c = 'blue', label = 'Iris-versicolour')
plt.scatter(x[a == 2, 0], x[a == 2, 1],
            s = 100, c = 'green', label = 'Iris-virginica')

# Plotting the centroids of the clusters
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:,1], 
            s = 100, c = 'yellow', label = 'Centroids')

plt.legend()

